version: "3"
services:

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
    - 5672:5672
    - 15672:15672

  consumer:
    build: consumer
    links:
    - rabbitmq
    command: python consumer.py
    volumes:
      - ./base:/usr/src/app/base
  producer:
    build: producer
    links:
    - rabbitmq
    command: python producer.py
    volumes:
      - ./base:/usr/src/app/base